version: '3.0'
services:
    web:
        build: .
        command: node ./src/index.js
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
        environment:
            - MONGO_URI=mongodb://mongodb:27017/tesse-backend-database
            - PORT=3000
    mongodb:
        image: mongo
        ports:
            - '27017:27017'
